SELECT ED.ID,
        CASE
            WHEN SIZE_OF_COLONY <= 100
            THEN 'LOW'
            WHEN SIZE_OF_COLONY BETWEEN 101 AND 1000
            THEN 'MEDIUM'
            ELSE 'HIGH'
        END SIZE
FROM ECOLI_DATA ED
ORDER BY ID;