SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM
(SELECT *, RANK() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RANK_ROW
FROM FISH_INFO) FI
LEFT JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FI.RANK_ROW <= 1
ORDER BY ID ASC;